# Generated by Django 3.2.23 on 2023-12-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRooms',
            new_name='ChatRoom',
        ),
    ]
